FROM alpine:3.8 as builder

RUN apk update
RUN apk add ca-certificates

FROM scratch

ENTRYPOINT [ "/snyk_exporter" ]
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY snyk_exporter /
