apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: snyk-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snyk-exporter
  template:
    metadata:
      name: snyk-exporter
      labels:
        app: snyk-exporter
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9532'
    spec:
      containers:
      - name: snyk-exporter
        image: quay.io/lunarway/snyk_exporter:latest
        args: ["--snyk.api-token", "$(SNYK_API_TOKEN)", "--log.level", "debug"]
        env:
        - name: SNYK_API_TOKEN
          valueFrom:
            secretKeyRef:
              key: snyk.api-token
              name: snyk-exporter
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9532
        readinessProbe:
          httpGet:
            path: /ready
            port: 9532
          initialDelaySeconds: 5
          periodSeconds: 30
          failureThreshold: 5
        ports:
        - name: scrape
          containerPort: 9532
