apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: snyk-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snyk-exporter
  template:
    metadata:
      name: snyk-exporter
      labels:
        app: snyk-exporter
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9532'
    spec:
      containers:
      - name: snyk-exporter
        image: quay.io/lunarway/snyk_exporter:v1.0.0
        args: ["--snyk.api-token", "YOUR_API_TOKEN", "--snyk.organization", "YOU_ORGANIZATION"]
        ports:
        - name: scrape
          containerPort: 9532
        